version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/NodeEttMulti
ApplicationStop:
    - location: scripts/stop_server.sh
ApplicationStart:
    - location: scripts/start_server.sh
